# backend/app/docker_compose.yml

services:
  db:
    image: postgres:15-alpine
    container_name: nibalink_db
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nibalink_net

  backend:
    build: ./backend
    container_name: nibalink_backend
    restart: always
    env_file: .env
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    depends_on:
      - db
    networks:
      - nibalink_net

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=${VITE_API_URL}
    container_name: nibalink_frontend
    restart: always
    networks:
      - nibalink_net

volumes:
  postgres_data:

networks:
  nibalink_net:
    driver: bridge