# nibalink_services_landing/docker-compose.yml

services:
  nibalink_landing: # Este es el nombre del servicio
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nibalink_services_landing # Este es el nombre que busca Nginx
    restart: always
    networks:
      - nibalink_net

networks:
  nibalink_net:
    external: true 
