# nibalink_services_landing/docker-compose.yml

services:
  nibalink_landing:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nibalink_services_landing
    ports:
      - "8080:80"
    restart: always
